# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: assistant_backend test and lint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'assistant_backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'assistant_backend/**'  
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:

  ci-content_management_backend:
    uses: ./.github/workflows/python_reusable.yml
    with:
      working-directory: assistant_backend
    secrets: inherit