name: assistant_commons build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'assistant_commons/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'assistant_commons/**'
  
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  assistant_commons_test:
    uses: ./.github/workflows/python_reusable.yml
    with:
      working-directory: assistant_commons
    secrets: inherit

  content_management_backend_build:
    needs: [assistant_commons_test]
    uses: ./.github/workflows/content_management_backend_build.yml
    secrets: inherit


  assistant_backend_build:
    needs: [assistant_commons_test]
    uses: ./.github/workflows/assistant_backend_build.yml
    secrets: inherit