name: assistant_backend build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'assistant_backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'assistant_backend/**'  
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:

  assistant_backend_test:
    uses: ./.github/workflows/python_reusable.yml
    with:
      working-directory: assistant_backend
    secrets: inherit

  build-image-assistant_backend:
      needs: assistant_backend_test
      uses: ./.github/workflows/docker_image_reusable.yml
      with:
        image-name: assistant_backend
        docker-file: assistant_backend/Dockerfile
        build-number: ${{ needs.assistant_backend_test.outputs.package_version }}-b${{ github.run_number }}
      secrets: inherit