name: content_management_frontend build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'content_management_frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'content_management_frontend/**'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./content_management_frontend
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v18.12.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'
        cache: 'npm'
    - run: npm ci
      working-directory: ./content_management_frontend
    - run: npm test
      working-directory: ./content_management_frontend
    - run: npm run build --if-present
      working-directory: ./content_management_frontend
