name: reusable build/push docker image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
        description: "Provides a name for the docker image"
      docker-file:
        required: true
        type: string
        description: "Path to dockerfile"
      build-number:
        required: true
        type: string
        description: "Dockerimage buildnumber tag"

      
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.image-name }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.docker-file }}
          tags: vmatic/${{ inputs.image-name}}:${{ inputs.build-number }}
          annotations: ${{ steps.meta.outputs.annotations }}
          push: true
